force-app/main/default/objects/Exemption__c/Exemption__c.object-meta.xml
<CustomObject>
    <label>Exemption</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Exemption Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exemption__c/fields/LandlordCountry__c.field-meta.xml
<CustomField>
    <fullName>LandlordCountry__c</fullName>
    <label>Landlord Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PRSE_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PRSE_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United Kingdom</fullName>
        <default>true</default>
        <label>United Kingdom</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Cameroon</fullName>
    </customValue>
    <description>List of countries to be used</description>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PRSE_RetrieveCountriesAction.cls
public with sharing class PRSE_RetrieveCountriesAction {

    public class Response {
        
        @InvocableVariable
        public String concatenatedCountries;

        public Response(String concatenatedCountries) {
            this.concatenatedCountries = concatenatedCountries;
        }
    }

    @InvocableMethod(
        label='Get countries from global value set' 
        description='Returns available countries for account registration.'
        category='PRS Exemption Register'
    )
    public static List<Response> getCountries() {
        DescribeFieldResult fieldResult = Exemption__c.LandlordCountry__c.getDescribe();
        List<PicklistEntry> values = fieldResult.getPicklistValues();
        String concatenatedCountries = '';
        for(PicklistEntry value :values) {
            concatenatedCountries += value.getValue() + '|';
        }
        return new List<Response>{ 
            new Response(
                concatenatedCountries.removeEnd('|')
            ) 
        };
    }
}