force-app/main/default/objects/Account/fields/DomesticNotificationsMailbox__c.field-meta.xml
<CustomField>
    <fullName>DomesticNotificationsMailbox__c</fullName>
    <label>Domestic Notifications Mailbox</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Custodian_Code__c.field-meta.xml
<CustomField>
    <fullName>Local_Custodian_Code__c</fullName>
    <label>Local Custodian Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LocalCustodianCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NonDomesticNotificationsMailbox__c.field-meta.xml
<CustomField>
    <fullName>NonDomesticNotificationsMailbox__c</fullName>
    <label>Non-domestic Notifications Mailbox</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Local_Authority.recordType-meta.xml
<RecordType>
    <fullName>Local_Authority</fullName>
    <active>true</active>
    <label>Local Authority</label>
</RecordType>

force-app/main/default/globalValueSets/LocalCustodianCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>114</fullName>
    </customValue>
    <customValue>
        <fullName>116</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>121</fullName>
    </customValue>
    <customValue>
        <fullName>230</fullName>
    </customValue>
    <customValue>
        <fullName>235</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>335</fullName>
    </customValue>
    <customValue>
        <fullName>340</fullName>
    </customValue>
    <customValue>
        <fullName>345</fullName>
    </customValue>
    <customValue>
        <fullName>350</fullName>
    </customValue>
    <customValue>
        <fullName>355</fullName>
    </customValue>
    <customValue>
        <fullName>360</fullName>
    </customValue>
    <customValue>
        <fullName>435</fullName>
    </customValue>
    <customValue>
        <fullName>440</fullName>
    </customValue>
    <customValue>
        <fullName>505</fullName>
    </customValue>
    <customValue>
        <fullName>510</fullName>
    </customValue>
    <customValue>
        <fullName>515</fullName>
    </customValue>
    <customValue>
        <fullName>520</fullName>
    </customValue>
    <customValue>
        <fullName>530</fullName>
    </customValue>
    <customValue>
        <fullName>535</fullName>
    </customValue>
    <customValue>
        <fullName>540</fullName>
    </customValue>
    <customValue>
        <fullName>650</fullName>
    </customValue>
    <customValue>
        <fullName>655</fullName>
    </customValue>
    <customValue>
        <fullName>660</fullName>
    </customValue>
    <customValue>
        <fullName>665</fullName>
    </customValue>
    <customValue>
        <fullName>724</fullName>
    </customValue>
    <customValue>
        <fullName>728</fullName>
    </customValue>
    <customValue>
        <fullName>734</fullName>
    </customValue>
    <customValue>
        <fullName>738</fullName>
    </customValue>
    <customValue>
        <fullName>5990</fullName>
    </customValue>
    <masterLabel>Local Custodian Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/test/classes/PRSE_RetrieveLAAccountActionTest.cls
@isTest
private class PRSE_RetrieveLAAccountActionTest {

    @isTest
    static void getAccounts_withNullLocalCustodianCodes_returnsEmptyAccountList() {
        //Arrange
        List<String> localcustodianCodes = null;

        //Act
        List<Account> accounts = PRSE_RetrieveLocalAuthorityAccountAction.getAccounts(localcustodianCodes);

        //Assert
        Assert.areEqual(0, accounts.size(), 'Incorrect number of accounts returned');
    }

    @isTest
    static void getAccounts_withEmptyLocalCustodianCodes_returnsEmptyAccountList() {
        //Arrange
        List<String> localcustodianCodes = new List<String>();

        //Act
        List<Account> accounts = PRSE_RetrieveLocalAuthorityAccountAction.getAccounts(localcustodianCodes);

        //Assert
        Assert.areEqual(0, accounts.size(), 'Incorrect number of accounts returned');
    }

    @isTest
    static void getAccounts_withNoLocalAuthorityRecordsTypes_returnsEmptyAccountList() {
        //Arrange
        List<String> localcustodianCodes = new List<String>{ '5990' };
        MockProvider mockProvider = new MockProvider();
        DatabaseWrapper mockDatabaseWrapper = (DatabaseWrapper) mockProvider.createMock(DatabaseWrapper.class);
        DatabaseWrapper.privilegedInstance = mockDatabaseWrapper;
        mockProvider.when(
            mockDatabaseWrapper.query(
                'SELECT Id, Name, SOBjectType ' +
                'FROM RecordType WHERE SOBjectType = \'Account\' AND Name = \'Local Authority\' LIMIT 1'
            )
        ).thenReturn(null);

        //Act
        List<Account> accounts = PRSE_RetrieveLocalAuthorityAccountAction.getAccounts(localcustodianCodes);

        //Assert
        Assert.areEqual(0, accounts.size(), 'Incorrect number of accounts returned');
    }

    @isTest
    static void getAccounts_withLocalAuthorityRecordsTypeButNoAccounts_returnsEmptyAccountList() {
        //Arrange
        List<String> localcustodianCodes = new List<String>{ '5990' };
        RecordType mockRecordType = new RecordType();
        mockRecordType.Id = SObjectUtil.generateIdForType('RecordType');
        mockRecordType.DeveloperName = 'Local_Authority';
        mockRecordType.Name = 'Local Authority';
        List<RecordType> recordTypesToReturn = new List<RecordType>{ mockRecordType };

        MockProvider mockProvider = new MockProvider();
        DatabaseWrapper mockDatabaseWrapper = (DatabaseWrapper) mockProvider.createMock(DatabaseWrapper.class);
        DatabaseWrapper.privilegedInstance = mockDatabaseWrapper;
        mockProvider.when(
            mockDatabaseWrapper.query(
                'SELECT Id, Name, SOBjectType ' +
                'FROM RecordType WHERE SOBjectType = \'Account\' AND Name = \'Local Authority\' LIMIT 1'
            )
        ).thenReturn(recordTypesToReturn);
        Map<String, Object> bindMap = new Map<String, Object> { 
            'localAuthorityRecordTypeId' => mockRecordType.Id,
            'localCustodianCode' => localCustodianCodes[0]
        };
        mockProvider.when(
            mockDatabaseWrapper.queryWithBinds(
                'SELECT Id, Name, Local_Custodian_Code__c, DomesticNotificationsMailbox__c, NonDomesticNotificationsMailbox__c ' +
                'FROM Account ' +
                'WHERE RecordTypeId = :localAuthorityRecordTypeId ' +
                'AND Local_Custodian_Code__c = :localCustodianCode',
                bindMap
            )
        ).thenReturn(new List<Account>());

        //Act
        List<Account> accounts = PRSE_RetrieveLocalAuthorityAccountAction.getAccounts(localcustodianCodes);

        //Assert
        Assert.areEqual(0, accounts.size(), 'Incorrect number of accounts returned');
    }

    @isTest
    static void getAccounts_withLocalAuthorityRecordsTypeAndMatchingAccounts_returnsAccountList() {
        //Arrange
        List<String> localcustodianCodes = new List<String>{ '5990' };
        RecordType mockRecordType = new RecordType();
        mockRecordType.Id = SObjectUtil.generateIdForType('RecordType');
        mockRecordType.DeveloperName = 'Local_Authority';
        mockRecordType.Name = 'Local Authority';
        List<RecordType> recordTypesToReturn = new List<RecordType>{ mockRecordType };
        List<Account> accountsToReturn = new List<Account>{ 
            new Account(
                Id = SObjectUtil.generateIdForType('Account'),
                Name = 'Test Account',
                Local_Custodian_Code__c = '5990',
                DomesticNotificationsMailbox__c = 'test@test1.com',
                NonDomesticNotificationsMailbox__c = 'test@test2.com'
            )
         };

        MockProvider mockProvider = new MockProvider();
        DatabaseWrapper mockDatabaseWrapper = (DatabaseWrapper) mockProvider.createMock(DatabaseWrapper.class);
        DatabaseWrapper.privilegedInstance = mockDatabaseWrapper;
        mockProvider.when(
            mockDatabaseWrapper.query(
                'SELECT Id, Name, SOBjectType ' +
                'FROM RecordType WHERE SOBjectType = \'Account\' AND Name = \'Local Authority\' LIMIT 1'
            )
        ).thenReturn(recordTypesToReturn);
        Map<String, Object> bindMap = new Map<String, Object> { 
            'localAuthorityRecordTypeId' => mockRecordType.Id,
            'localCustodianCode' => localCustodianCodes[0]
        };
        mockProvider.when(
            mockDatabaseWrapper.queryWithBinds(
                'SELECT Id, Name, Local_Custodian_Code__c, DomesticNotificationsMailbox__c, NonDomesticNotificationsMailbox__c ' +
                'FROM Account ' +
                'WHERE RecordTypeId = :localAuthorityRecordTypeId ' +
                'AND Local_Custodian_Code__c = :localCustodianCode',
                bindMap
            )
        ).thenReturn(accountsToReturn);

        //Act
        List<Account> accounts = PRSE_RetrieveLocalAuthorityAccountAction.getAccounts(localcustodianCodes);

        //Assert
        Assert.areEqual(1, accounts.size(), 'Incorrect number of accounts returned');
        Account localAuthorityAccount = accounts[0];
        Assert.areEqual('Test Account', localAuthorityAccount.Name, 'Incorrect name for local authority account');
        Assert.areEqual('5990', localAuthorityAccount.Local_Custodian_Code__c, 'Incorrect local custodian code for local authority account');
        Assert.areEqual('test@test1.com', localAuthorityAccount.DomesticNotificationsMailbox__c, 'Incorrect domestic email for local authority account');
        Assert.areEqual('test@test2.com', localAuthorityAccount.NonDomesticNotificationsMailbox__c, 'Incorrect non-domestic email for local authority account');
    }
}