force-app/main/default/objects/Account/fields/DomesticNotificationsMailbox__c.field-meta.xml
<CustomField>
    <fullName>DomesticNotificationsMailbox__c</fullName>
    <label>Domestic Notifications Mailbox</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Local_Custodian_Code__c.field-meta.xml
<CustomField>
    <fullName>Local_Custodian_Code__c</fullName>
    <label>Local Custodian Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LocalCustodianCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NonDomesticNotificationsMailbox__c.field-meta.xml
<CustomField>
    <fullName>NonDomesticNotificationsMailbox__c</fullName>
    <label>Non-domestic Notifications Mailbox</label>
    <type>Email</type>
</CustomField>

force-app/main/default/globalValueSets/LocalCustodianCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>114</fullName>
    </customValue>
    <customValue>
        <fullName>116</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>121</fullName>
    </customValue>
    <customValue>
        <fullName>230</fullName>
    </customValue>
    <customValue>
        <fullName>235</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>335</fullName>
    </customValue>
    <customValue>
        <fullName>340</fullName>
    </customValue>
    <customValue>
        <fullName>345</fullName>
    </customValue>
    <customValue>
        <fullName>350</fullName>
    </customValue>
    <customValue>
        <fullName>355</fullName>
    </customValue>
    <customValue>
        <fullName>360</fullName>
    </customValue>
    <customValue>
        <fullName>435</fullName>
    </customValue>
    <customValue>
        <fullName>440</fullName>
    </customValue>
    <customValue>
        <fullName>505</fullName>
    </customValue>
    <customValue>
        <fullName>510</fullName>
    </customValue>
    <customValue>
        <fullName>515</fullName>
    </customValue>
    <customValue>
        <fullName>520</fullName>
    </customValue>
    <customValue>
        <fullName>530</fullName>
    </customValue>
    <customValue>
        <fullName>535</fullName>
    </customValue>
    <customValue>
        <fullName>540</fullName>
    </customValue>
    <customValue>
        <fullName>650</fullName>
    </customValue>
    <customValue>
        <fullName>655</fullName>
    </customValue>
    <customValue>
        <fullName>660</fullName>
    </customValue>
    <customValue>
        <fullName>665</fullName>
    </customValue>
    <customValue>
        <fullName>724</fullName>
    </customValue>
    <customValue>
        <fullName>728</fullName>
    </customValue>
    <customValue>
        <fullName>734</fullName>
    </customValue>
    <customValue>
        <fullName>738</fullName>
    </customValue>
    <masterLabel>Local Custodian Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PRSE_RetrieveLocalAuthorityAccountAction.cls
public without sharing class PRSE_RetrieveLocalAuthorityAccountAction {
    final static digitalmodus.SystemLogService errorLoggingService = new digitalmodus.SystemLogService('PRSE_RetrieveLocalAuthorityAccountAction');

    @InvocableVariable(label='Local Custodian Codes' required=true)
    public List<String> localCustodianCodes;

    @InvocableMethod(
        label='Fetch Local Authority Accounts'
        description='Returns Local Authority Accounts for a given Local Custodian Code.'
        category='PRS Exemption Register'
    )
    public static List<Account> getAccounts(List<String> localCustodianCodes) {
        List<Account> matchingAccounts = new List<Account>();
        if (localCustodianCodes == null || localCustodianCodes.isEmpty()) {
            return matchingAccounts;
        }
        try {
            String localCustodianCode = localCustodianCodes[0];
            Id localAuthorityRecordTypeId = ((List<RecordType>) DatabaseWrapper.getPrivilegedInstance()
                .query(
                    'SELECT Id, Name, SOBjectType FROM RecordType WHERE SOBjectType = \'Account\' AND Name = \'Local Authority\' LIMIT 1'
                ))[0]?.Id;
            if (localAuthorityRecordTypeId == null) {
                return matchingAccounts;
            }

            Map<String, Object> bindMap = new Map<String, Object> { 
                'localAuthorityRecordTypeId' => localAuthorityRecordTypeId,
                'localCustodianCode' => localCustodianCode
            };
            matchingAccounts = DatabaseWrapper.getPrivilegedInstance().queryWithBinds(
                'SELECT Id, Name, Local_Custodian_Code__c, DomesticNotificationsMailbox__c, NonDomesticNotificationsMailbox__c ' +
                'FROM Account ' +
                'WHERE RecordTypeId = :localAuthorityRecordTypeId ' +
                'AND Local_Custodian_Code__c = :localCustodianCode', 
                bindMap
            );
        } catch (Exception e) {
            errorLoggingService.setLogCode('PRSE_RetrieveLocalAuthorityAccountAction')
                .setTriggeringAutomationName('getAccounts')
                .setMessage(e.getMessage())
                .setLogSourceCategory(digitalmodus.SystemLogService.LogSourceCategory.APEX_CLASS)
                .publish();
        }

        return matchingAccounts;
    }
}