force-app/main/default/objects/Account/fields/Local_Custodian_Code__c.field-meta.xml
<CustomField>
    <fullName>Local_Custodian_Code__c</fullName>
    <label>Local Custodian Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LocalCustodianCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exemption__c/Exemption__c.object-meta.xml
<CustomObject>
    <label>Exemption</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Exemption Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exemption__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>Exemptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/AdditionalInformation__c.field-meta.xml
<CustomField>
    <fullName>AdditionalInformation__c</fullName>
    <label>Additional Information</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/LandlordBusinessName__c.field-meta.xml
<CustomField>
    <fullName>LandlordBusinessName__c</fullName>
    <label>Landlord Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/LandlordLastName__c.field-meta.xml
<CustomField>
    <fullName>LandlordLastName__c</fullName>
    <label>Landlord Last Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/Local_Custodian_Code__c.field-meta.xml
<CustomField>
    <fullName>Local_Custodian_Code__c</fullName>
    <label>Local Custodian Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LocalCustodianCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/PropertyAddress__c.field-meta.xml
<CustomField>
    <fullName>PropertyAddress__c</fullName>
    <label>Property Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/PropertyCounty__c.field-meta.xml
<CustomField>
    <fullName>PropertyCounty__c</fullName>
    <label>Property County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/Ref_Legacy__c.field-meta.xml
<CustomField>
    <fullName>Ref_Legacy__c</fullName>
    <description>Holds previous system reference</description>
    <label>Ref Legacy</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exemption__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Needs update</fullName>
            </value>
            <value>
                <fullName>Penalty sent</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exemption_Type__c/Exemption_Type__c.object-meta.xml
<CustomObject>
    <label>Exemption Type</label>
    <nameField>
        <label>Exemption Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exemption Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exemption_Type__c/fields/AdditionalInformation__c.field-meta.xml
<CustomField>
    <fullName>AdditionalInformation__c</fullName>
    <label>Additional Information</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exemption_Type__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exemption_Type__c/fields/IsCommercial__c.field-meta.xml
<CustomField>
    <fullName>IsCommercial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCommercial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/LocalCustodianCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>114</fullName>
    </customValue>
    <customValue>
        <fullName>116</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>121</fullName>
    </customValue>
    <customValue>
        <fullName>230</fullName>
    </customValue>
    <customValue>
        <fullName>235</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>335</fullName>
    </customValue>
    <customValue>
        <fullName>340</fullName>
    </customValue>
    <customValue>
        <fullName>345</fullName>
    </customValue>
    <customValue>
        <fullName>350</fullName>
    </customValue>
    <customValue>
        <fullName>355</fullName>
    </customValue>
    <customValue>
        <fullName>360</fullName>
    </customValue>
    <customValue>
        <fullName>435</fullName>
    </customValue>
    <customValue>
        <fullName>440</fullName>
    </customValue>
    <customValue>
        <fullName>505</fullName>
    </customValue>
    <customValue>
        <fullName>510</fullName>
    </customValue>
    <customValue>
        <fullName>515</fullName>
    </customValue>
    <customValue>
        <fullName>520</fullName>
    </customValue>
    <customValue>
        <fullName>530</fullName>
    </customValue>
    <customValue>
        <fullName>535</fullName>
    </customValue>
    <customValue>
        <fullName>540</fullName>
    </customValue>
    <customValue>
        <fullName>650</fullName>
    </customValue>
    <customValue>
        <fullName>655</fullName>
    </customValue>
    <customValue>
        <fullName>660</fullName>
    </customValue>
    <customValue>
        <fullName>665</fullName>
    </customValue>
    <customValue>
        <fullName>724</fullName>
    </customValue>
    <customValue>
        <fullName>728</fullName>
    </customValue>
    <customValue>
        <fullName>734</fullName>
    </customValue>
    <customValue>
        <fullName>738</fullName>
    </customValue>
    <customValue>
        <fullName>4610</fullName>
    </customValue>
    <customValue>
        <fullName>5990</fullName>
    </customValue>
    <masterLabel>Local Custodian Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/test/classes/LocalCustodianCodeAssignmentJobTest.cls
@isTest
private class LocalCustodianCodeAssignmentJobTest {

    @isTest
    static void execute_withNoValidRecordsToProcess_noUpdatesMade() {
        //Arrange
        Account testAccount = new Account(Name = 'Test');
        insert testAccount;

        Exemption_Type__c exemptionType1 = new Exemption_Type__c(
            Name = 'Type 1',
            Code__c = 'T001',
            IsCommercial__c = false
        );
        Exemption_Type__c exemptionType2 = new Exemption_Type__c(
            Name = 'Type 2',
            Code__c = 'T002',
            IsCommercial__c = false
        );
        insert new List<Exemption_Type__c> { exemptionType1, exemptionType2 };

        Exemption__c draftExemption = new Exemption__c(
            Status__c = 'Draft', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Draft exemption',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 1'
        );
        Exemption__c receivedExemption1 = new Exemption__c(
            Status__c = 'Received', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Received exemption 1',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential'
        );
        Exemption__c receivedExemption2 = new Exemption__c(
            Status__c = 'Received', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Received exemption 2',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Local_Custodian_Code__c = '4610',
            Ref_Legacy__c = 'TEST 3'
        );
        Exemption__c updatedExemption = new Exemption__c(
            Status__c = 'Updated', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Updated exemption',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 4'
        );
        insert new List<Exemption__c> { draftExemption, receivedExemption1, receivedExemption2, updatedExemption };

        //Act
        Test.startTest();
        System.enqueueJob(new LocalCustodianCodeAssignmentJob(), 0);
        Test.stopTest();

        //Assert
        ErrorLogChecker.checkNoErrors();
        Assert.isNull(draftExemption.Local_Custodian_Code__c, 'Expected draft exemption local custodian code to be empty');
        Assert.isNull(receivedExemption1.Local_Custodian_Code__c, 'Expected received exemption local custodian code to be empty');
        Assert.isNull(updatedExemption.Local_Custodian_Code__c, 'Expected updated exemption local custodian code to be empty');
    }

    @isTest
    static void execute_withRecordsToProcess_updatesRecordWithLocalCustodianCode() {
        //Arrange
        Account testAccount = new Account(Name = 'Test');
        insert testAccount;

        Exemption_Type__c exemptionType1 = new Exemption_Type__c(
            Name = 'Type 1',
            Code__c = 'T001',
            IsCommercial__c = false
        );
        Exemption_Type__c exemptionType2 = new Exemption_Type__c(
            Name = 'Type 2',
            Code__c = 'T002',
            IsCommercial__c = false
        );
        insert new List<Exemption_Type__c> { exemptionType1, exemptionType2 };

        Exemption__c draftExemption = new Exemption__c(
            Status__c = 'Draft', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Draft exemption',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 1'
        );
        Exemption__c receivedExemption1 = new Exemption__c(
            Status__c = 'Received', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Received exemption 1',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 2'
        );
        Exemption__c receivedExemption2 = new Exemption__c(
            Status__c = 'Received', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Received exemption 2',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Local_Custodian_Code__c = '4610',
            Ref_Legacy__c = 'TEST 3'
        );
        Exemption__c updatedExemption = new Exemption__c(
            Status__c = 'Updated', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Updated exemption',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 4'
        );
        insert new List<Exemption__c> { draftExemption, receivedExemption1, receivedExemption2, updatedExemption };

        DeliveryPointAddress dpaToReturn = new DeliveryPointAddress();
        dpaToReturn.LOCAL_CUSTODIAN_CODE = 5990;
        String dpaQueryAddress = 
            receivedExemption1.PropertyAddress__c + ', ' + 
            receivedExemption1.PropertyCity__c + ', ' + 
            receivedExemption1.PropertyCounty__c + ', ' + 
            receivedExemption1.PropertyPostcode__c;
        MockProvider mockProvider = new MockProvider();
        System.debug('dpaQueryAddress: ' + dpaQueryAddress);
        OSPlacesInteractionService.API mockLayer = (OSPlacesInteractionService.API) mockProvider.createMock(OSPlacesInteractionServiceLayer.class);
        OSPlacesInteractionServiceLayer.instance = mockLayer;
        mockProvider.when(mockLayer.matchAddressForEnglandOrWalesOnly(dpaQueryAddress)).thenReturn(new List<DeliveryPointAddress>{ dpaToReturn });

        //Act
        Test.startTest();
        System.enqueueJob(new LocalCustodianCodeAssignmentJob(), 0);
        Test.stopTest();

        //Assert
        ErrorLogChecker.checkNoErrors();
        Assert.isNull(draftExemption.Local_Custodian_Code__c, 'Expected draft exemption local custodian code to be empty');
        Assert.areEqual('4610', receivedExemption2.Local_Custodian_Code__c, 'Expected received exemption 2 local custodian code to be 4610');
        Assert.isNull(updatedExemption.Local_Custodian_Code__c, 'Expected updated exemption local custodian code to be empty');

        Exemption__c expectedUpdatedExemption = [SELECT Id, Local_Custodian_Code__c FROM Exemption__c WHERE Ref_Legacy__c = 'TEST 2' LIMIT 1];
        Assert.areEqual('5990', expectedUpdatedExemption.Local_Custodian_Code__c, 'Expected received exemption 1 local custodian code to be 5990');
    }

    @isTest
    static void execute_withExemptionInCallout_logsError() {
        //Arrange
        Account testAccount = new Account(Name = 'Test');
        insert testAccount;

        Exemption_Type__c exemptionType1 = new Exemption_Type__c(
            Name = 'Type 1',
            Code__c = 'T001',
            IsCommercial__c = false
        );
        Exemption_Type__c exemptionType2 = new Exemption_Type__c(
            Name = 'Type 2',
            Code__c = 'T002',
            IsCommercial__c = false
        );
        insert new List<Exemption_Type__c> { exemptionType1, exemptionType2 };

        Exemption__c draftExemption = new Exemption__c(
            Status__c = 'Draft', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Draft exemption',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 1'
        );
        Exemption__c receivedExemption1 = new Exemption__c(
            Status__c = 'Received', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Received exemption 1',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 2'
        );
        Exemption__c receivedExemption2 = new Exemption__c(
            Status__c = 'Received', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Received exemption 2',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Local_Custodian_Code__c = '4610',
            Ref_Legacy__c = 'TEST 3'
        );
        Exemption__c updatedExemption = new Exemption__c(
            Status__c = 'Updated', 
            Account__c = testAccount.Id,
            Published__c = true,
            AdditionalInformation__c = 'Updated exemption',
            LandlordBusinessName__c = 'Test Business Name',
            LandlordFirstName__c = 'Test First Name',
            LandlordLastName__c = 'Test Last Name',
            PropertyAddress__c = 'Address 123',
            PropertyCity__c = 'London',
            PropertyCounty__c = 'Greater London',
            PropertyPostcode__c = 'SW1A 2AW',
            PropertyType__c = 'Residential',
            Ref_Legacy__c = 'TEST 4'
        );
        insert new List<Exemption__c> { draftExemption, receivedExemption1, receivedExemption2, updatedExemption };

        String dpaQueryAddress = 
            receivedExemption1.PropertyAddress__c + ', ' + 
            receivedExemption1.PropertyCity__c + ', ' + 
            receivedExemption1.PropertyCounty__c + ', ' + 
            receivedExemption1.PropertyPostcode__c;
        MockProvider mockProvider = new MockProvider();
        OSPlacesInteractionService.API mockLayer = (OSPlacesInteractionService.API) mockProvider.createMock(OSPlacesInteractionServiceLayer.class);
        OSPlacesInteractionServiceLayer.instance = mockLayer;
        mockProvider.when(mockLayer.matchAddressForEnglandOrWalesOnly(dpaQueryAddress)).thenThrow(new Exceptions.CustomException('An error has occured'));

        //Act
        Test.startTest();
        System.enqueueJob(new LocalCustodianCodeAssignmentJob(), 0);
        Test.stopTest();

        //Assert
        Exemption__c expectedUpdatedExemptionToError = [SELECT Id FROM Exemption__c WHERE Ref_Legacy__c = 'TEST 2' LIMIT 1];
        String expectedErrorMessage = 'execute for record ' + expectedUpdatedExemptionToError.Id + ' with error: An error has occured';
        List<digitalmodus__System_Log__c> errorLogs = [
            SELECT Id, digitalmodus__Log_Message__c, digitalmodus__Log_Code__c,  digitalmodus__Related_Service__c 
            FROM digitalmodus__System_Log__c
        ];
        system.debug(expectedErrorMessage);
        system.debug(errorLogs);
        ErrorLogChecker.checkErrorForServiceAndMethod('LocalCustodianCodeAssignmentJob', 'execute', expectedErrorMessage);
    }
}